# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0b3 on Wed Mar 14 08:52:52 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((250, 150))
        self.Anmeldename = wx.StaticText(self, wx.ID_ANY, "Anmeldename")
        self.name = wx.TextCtrl(self, wx.ID_ANY, "Hier Anmeldename eingeben")
        self.Passwort = wx.StaticText(self, wx.ID_ANY, "Passwort")
        self.passw = wx.TextCtrl(self, wx.ID_ANY, "Hier Paswort eingeben")
        self.weiter = wx.Button(self, wx.ID_ANY, "Weiter")
        self.ende = wx.Button(self, wx.ID_ANY, "Beenden")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(0, 2, 0, 0)
        grid_sizer_1.Add(self.Anmeldename, 0, 0, 0)
        grid_sizer_1.Add(self.name, 0, 0, 0)
        grid_sizer_1.Add(self.Passwort, 0, 0, 0)
        grid_sizer_1.Add(self.passw, 0, 0, 0)
        grid_sizer_1.Add(self.weiter, 0, 0, 0)
        grid_sizer_1.Add(self.ende, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame
# Minimum um ein Fenster darzustellen
app = wx.App()
frame = MyFrame(None)
frame.Show()
app.MainLoop()
