# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0b3 on Mon Feb 12 14:12:05 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((250, 411))
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "config")
        self.button_3 = wx.Button(self, wx.ID_ANY, "Laden")
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "Anmeldename")
        self.text_ctrl_3 = wx.TextCtrl(self, wx.ID_ANY, "Passwort")
        self.text_ctrl_4 = wx.TextCtrl(self, wx.ID_ANY, "Freigabe")
        self.text_ctrl_5 = wx.TextCtrl(self, wx.ID_ANY, "Schüler")
        self.button_2 = wx.Button(self, wx.ID_ANY, "Weiter")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Anmeldung")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        grid_sizer_1 = wx.GridSizer(7, 2, 0, 0)
        label_1 = wx.StaticText(self, wx.ID_ANY, "Konfiguration", style=wx.ALIGN_CENTER)
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        grid_sizer_1.Add(self.button_3, 0, wx.ALIGN_RIGHT | wx.TOP, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "Anmeldename", style=wx.ALIGN_CENTER)
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER, 0)
        label_3 = wx.StaticText(self, wx.ID_ANY, "Passwort", style=wx.ALIGN_CENTER)
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.text_ctrl_3, 0, wx.ALIGN_CENTER, 0)
        label_4 = wx.StaticText(self, wx.ID_ANY, "Freigabe", style=wx.ALIGN_CENTER)
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.text_ctrl_4, 0, wx.ALIGN_CENTER, 0)
        label_5 = wx.StaticText(self, wx.ID_ANY, "Rolle", style=wx.ALIGN_CENTER)
        grid_sizer_1.Add(label_5, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.text_ctrl_5, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.button_2, 0, wx.ALIGN_CENTER, 0)
        self.SetSizer(grid_sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame
class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MyFrame(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class MyApp
app = MyApp(0)
# print (self.text_ctrl_1)
app.MainLoop()
